apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    name: webServer
spec:
  containers:
  - name: pod-demo
    image: zxcvbnius/docker-demo
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
