apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
spec:
  replicas: 3 # 定義Pod數量
  selector:
    app: hello-pod-v1 # 指定要選擇的Pod的條件(labels)
  template: # 定義pod,含Pod的labels以及Pod中要運行的container。
    metadata:
      labels:
        app: hello-pod-v1
    spec:
      containers:
        - name: my-pod
          image: zxcvbnius/docker-demo
          ports:
          - containerPort: 3000