apiVersion: v1
kind: ConfigMap
metadata:
  name: mb-frontend-nginx
data:
  default.conf: |
    log_format detail '$remote_addr - $remote_user [$time_local] '                                                                                                                  
                      '"$request" $status $bytes_sent '
                      'req_time($request_time) '
                      'upstream_time($upstream_response_time) '
                      '"$http_referer" "$http_user_agent" "$gzip_ratio" $pipe XFF($http_x_forwarded_for)';

    upstream mb-mobile-upstream {
        server mb-mobile-frontend:80;
    }
    upstream ws-upstream {
        server mb-websocket:6003;
    }
    map $request_uri $redirect_uri {
        /           /sport/index.html;
        /sport/     /sport/index.html;
        /sport/m/   /sport/m/index.html;
    }
    map $request_uri $rewrite_request_uri {
        ~/mb(/.*) $1;
    }

    server {
        listen 80;
        server_name in-sports.com in-sports888.com;

        root /usr/share/nginx/html/;

        access_log /var/log/nginx/access.log detail;
        error_log /var/log/nginx/error.log debug;
        
        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        location ~ ^/ws-in {
            proxy_pass http://ws-upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_cache_bypass $http_upgrade;
        }

        location @php {
            rewrite ^/mb(/.*)$ /index.php last;
        }

        location ~ \.php$ {
            root /var/www/html/public/;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            fastcgi_pass mb-backend-php-fpm:9000;
            fastcgi_index index.php;
            include /etc/nginx/fastcgi_params;
            fastcgi_param REQUEST_URI $rewrite_request_uri;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ ^/sport/m(/.*)$ {
            proxy_pass http://mb-mobile-upstream$1;
        }
        location ~ ^/ {
            
            if ($redirect_uri) {
                return 302 $redirect_uri;
            }
            try_files $uri @php;
        }
    }

    server {
        
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
          return 404;
        }
    }
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mb-frontend
  labels:
    app: mb-frontend
spec:
  replicas: 5
  minReadySeconds: 20
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: mb-frontend
    spec:
      restartPolicy: Always
      containers:
        - name: mb-frontend
          image: gcr.io/rd1-resources/melon_front_member-production:latest
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-config
          configMap: 
            name: mb-frontend-nginx